@startuml usecase

:Developer:-->(Mengupload \n update baru)
:Developer:-->(Melihat \n log update)
:Developer:->(Melihat informasi \n update terbaru)
:Developer:->(Membuat \n project baru)
(Mengubah \n informasi project)<-:Developer:
(Mengubah \n informasi update)<-:Developer:
(Memilih lokasi \n penerapan update)<--:Developer:
(Menampilkan lokasi \n pada log update)<--:Developer:

:User:->(Melakukan \n pemeriksaan update)
:User:->(Mengkonfirmasi \n pengunduhan update)
:User:-->(Mengkonfirmasi \n penerapan update)
:User:-->(Mendapatkan notifikasi \n secara otomatis)
(Melihat \n proses pengunduhan)<-:User:
(Melakukan pemeriksaan update \n saat berpindah lokasi)<--:User:

@enduml