name: Backend workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install depedency
        run: |
          cd code-send-backend
          yarn
      - name: Run unit test
        env:
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: |
          cd code-send-backend
          yarn test
