name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
